//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.01 at 08:08:42 AM CDT 
//


package gov.cdc.cdsi.supportingdata.mapping;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.cdc.cdsi.supportingdata.mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.cdc.cdsi.supportingdata.mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AntigenSupportingData }
     * 
     */
    public AntigenSupportingData createAntigenSupportingData() {
        return new AntigenSupportingData();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series }
     * 
     */
    public AntigenSupportingData.Series createAntigenSupportingDataSeries() {
        return new AntigenSupportingData.Series();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose createAntigenSupportingDataSeriesSeriesDose() {
        return new AntigenSupportingData.Series.SeriesDose();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.ConditionalSkip }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.ConditionalSkip createAntigenSupportingDataSeriesSeriesDoseConditionalSkip() {
        return new AntigenSupportingData.Series.SeriesDose.ConditionalSkip();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set createAntigenSupportingDataSeriesSeriesDoseConditionalSkipSet() {
        return new AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.Interval }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.Interval createAntigenSupportingDataSeriesSeriesDoseInterval() {
        return new AntigenSupportingData.Series.SeriesDose.Interval();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.Indication }
     * 
     */
    public AntigenSupportingData.Series.Indication createAntigenSupportingDataSeriesIndication() {
        return new AntigenSupportingData.Series.Indication();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications }
     * 
     */
    public AntigenSupportingData.Contraindications createAntigenSupportingDataContraindications() {
        return new AntigenSupportingData.Contraindications();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications.Vaccine }
     * 
     */
    public AntigenSupportingData.Contraindications.Vaccine createAntigenSupportingDataContraindicationsVaccine() {
        return new AntigenSupportingData.Contraindications.Vaccine();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications.Vaccine.Contraindication }
     * 
     */
    public AntigenSupportingData.Contraindications.Vaccine.Contraindication createAntigenSupportingDataContraindicationsVaccineContraindication() {
        return new AntigenSupportingData.Contraindications.Vaccine.Contraindication();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications.VaccineGroup }
     * 
     */
    public AntigenSupportingData.Contraindications.VaccineGroup createAntigenSupportingDataContraindicationsVaccineGroup() {
        return new AntigenSupportingData.Contraindications.VaccineGroup();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Immunity }
     * 
     */
    public AntigenSupportingData.Immunity createAntigenSupportingDataImmunity() {
        return new AntigenSupportingData.Immunity();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Immunity.DateOfBirth }
     * 
     */
    public AntigenSupportingData.Immunity.DateOfBirth createAntigenSupportingDataImmunityDateOfBirth() {
        return new AntigenSupportingData.Immunity.DateOfBirth();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SelectSeries }
     * 
     */
    public AntigenSupportingData.Series.SelectSeries createAntigenSupportingDataSeriesSelectSeries() {
        return new AntigenSupportingData.Series.SelectSeries();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.Age }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.Age createAntigenSupportingDataSeriesSeriesDoseAge() {
        return new AntigenSupportingData.Series.SeriesDose.Age();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.AllowableInterval }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.AllowableInterval createAntigenSupportingDataSeriesSeriesDoseAllowableInterval() {
        return new AntigenSupportingData.Series.SeriesDose.AllowableInterval();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.PreferableVaccine }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.PreferableVaccine createAntigenSupportingDataSeriesSeriesDosePreferableVaccine() {
        return new AntigenSupportingData.Series.SeriesDose.PreferableVaccine();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.AllowableVaccine }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.AllowableVaccine createAntigenSupportingDataSeriesSeriesDoseAllowableVaccine() {
        return new AntigenSupportingData.Series.SeriesDose.AllowableVaccine();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.InadvertentVaccine }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.InadvertentVaccine createAntigenSupportingDataSeriesSeriesDoseInadvertentVaccine() {
        return new AntigenSupportingData.Series.SeriesDose.InadvertentVaccine();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.SeasonalRecommendation }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.SeasonalRecommendation createAntigenSupportingDataSeriesSeriesDoseSeasonalRecommendation() {
        return new AntigenSupportingData.Series.SeriesDose.SeasonalRecommendation();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set.Condition }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set.Condition createAntigenSupportingDataSeriesSeriesDoseConditionalSkipSetCondition() {
        return new AntigenSupportingData.Series.SeriesDose.ConditionalSkip.Set.Condition();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.SeriesDose.Interval.FromRelevantObs }
     * 
     */
    public AntigenSupportingData.Series.SeriesDose.Interval.FromRelevantObs createAntigenSupportingDataSeriesSeriesDoseIntervalFromRelevantObs() {
        return new AntigenSupportingData.Series.SeriesDose.Interval.FromRelevantObs();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Series.Indication.ObservationCode }
     * 
     */
    public AntigenSupportingData.Series.Indication.ObservationCode createAntigenSupportingDataSeriesIndicationObservationCode() {
        return new AntigenSupportingData.Series.Indication.ObservationCode();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications.Vaccine.Contraindication.ContraindicatedVaccine }
     * 
     */
    public AntigenSupportingData.Contraindications.Vaccine.Contraindication.ContraindicatedVaccine createAntigenSupportingDataContraindicationsVaccineContraindicationContraindicatedVaccine() {
        return new AntigenSupportingData.Contraindications.Vaccine.Contraindication.ContraindicatedVaccine();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Contraindications.VaccineGroup.Contraindication }
     * 
     */
    public AntigenSupportingData.Contraindications.VaccineGroup.Contraindication createAntigenSupportingDataContraindicationsVaccineGroupContraindication() {
        return new AntigenSupportingData.Contraindications.VaccineGroup.Contraindication();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Immunity.ClinicalHistory }
     * 
     */
    public AntigenSupportingData.Immunity.ClinicalHistory createAntigenSupportingDataImmunityClinicalHistory() {
        return new AntigenSupportingData.Immunity.ClinicalHistory();
    }

    /**
     * Create an instance of {@link AntigenSupportingData.Immunity.DateOfBirth.Exclusion }
     * 
     */
    public AntigenSupportingData.Immunity.DateOfBirth.Exclusion createAntigenSupportingDataImmunityDateOfBirthExclusion() {
        return new AntigenSupportingData.Immunity.DateOfBirth.Exclusion();
    }

}
